#!/usr/bin/env bash

NODE_ENV=development forever start -a -o ntrapy.log -e err.log --minUptime 200 --spinSleepTime 1000 -w ntrapy.js
pkill -f "coffee -w -c -o source/js source/coffee"
coffee -w -c -o source/js source/coffee &>> coffee.log &
